#!/usr/bin/env python

import pickle
import lxml.html
import requests

cookie_pkl='cookie.pkl'

with open('account.txt') as f:
    username,password=(line[:-1] for line in f)

url='https://beta.atcoder.jp/login'

res=requests.get(url)
dom=lxml.html.fromstring(res.text)

csrf_token=dom.xpath('//form[@action="/login"]/input[@name="csrf_token"]/@value')[0]

data={'username':username,'password':password,'csrf_token':csrf_token}

print('login...',end='',flush=True)
res=requests.post(url,cookies=res.cookies,data=data)
with open(cookie_pkl,'wb') as f:
    pickle.dump(res.cookies,f)
print('finish.')

