#!/usr/bin/env python

import os.path
import pickle
import sys
import click
import lxml.html
import requests


# ======================================================================
contest='abc001'
cookie_pkl='cookie.pkl'

lang_ids={
    'cpp': 3003,
    'py': 3023,  # CPython
    #'py': 3510,  # PyPy
    'txt': 3027,  # Text
}
# ======================================================================


@click.command()
@click.argument('file',type=click.Path(exists=True))
def submit(file):
    click.confirm(f'Do you want to submit {file} to {contest}?',abort=True)

    file=sys.argv[1]
    with open(file,encoding='utf-8') as f:
        source_code=f.read()

    with open(cookie_pkl,'rb') as f:
        cookies=pickle.load(f)

    url=f'https://beta.atcoder.jp/contests/{contest}/submit'
    res=requests.get(url,cookies=cookies)

    dom=lxml.html.fromstring(res.text)
    task_ids={e.text[0]:e.attrib['value'] for e in dom.xpath('//select[@id="select-task"]/option')}
    csrf_token=dom.xpath(f'//form[@action="/contests/{contest}/submit"]/input[@name="csrf_token"]/@value')[0]

    pre,ext=os.path.splitext(file)
    task_id=task_ids[pre[0]]
    lang_id=lang_ids[ext[1:]]

    data={
        'data.TaskScreenName':task_id,
        'data.LanguageId':lang_id,
        'sourceCode':source_code,
        'csrf_token':csrf_token,
    }

    print('submit...',end='',flush=True)
    requests.post(url,cookies=cookies,data=data)
    print('finish.')


submit()
