#!/usr/bin/env python

import os.path
import pickle
import sys
import lxml.html
import requests

# ======================================================================
contest='abc001'
cookie_pkl='cookie.pkl'

lang_ids={
    'cpp': 3003,
    'py': 3023,  # CPython
    #'py': 3510,  # PyPy
    'txt': 3027,  # Text
}
# ======================================================================

if len(sys.argv)!=2:
    print('Usage: python submit.py FILE')
    raise SystemExit

submit_file=sys.argv[1]
with open(submit_file) as f:
    source_code=f.read()

with open(cookie_pkl,'rb') as f:
    cookies=pickle.load(f)

url=f'https://beta.atcoder.jp/contests/{contest}/submit'
res=requests.get(url,cookies=cookies)

dom=lxml.html.fromstring(res.text)
task_ids={e.text[0]:e.attrib['value'] for e in dom.xpath('//select[@id="select-task"]/option')}
csrf_token=dom.xpath(f'//form[@action="/contests/{contest}/submit"]/input[@name="csrf_token"]/@value')[0]

pre,ext=os.path.splitext(submit_file)
task_id=task_ids[pre[0]]
lang_id=lang_ids[ext[1:]]

data={
    'data.TaskScreenName':task_id,
    'data.LanguageId':lang_id,
    'sourceCode':source_code,
    'csrf_token':csrf_token,
}

print('submit...',end='',flush=True)
res=requests.post(url,cookies=cookies,data=data)
print(f'finish.')
